name: Run Telegram Forwarding Bot

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 * * * *' # Run hourly (adjust as needed)

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==20.3

    - name: Run Telegram bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        My.Chat.id: ${{ secrets.My.Chat.id }}
      run: |
        python telegram_bot/forward_bot.py