name: Send Files to Telegram

on:
  push:
    branches:
      - main

jobs:
  send_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Download files from GitHub repository
        run: |
          curl -sL https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ -o list_files.tar.gz
          tar -xzvf list_files.tar.gz -C ./list

      - name: Send files to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          for file in ./list/*; do
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
              -H "Content-Type: application/json" \
              -d '{"chat_id":"'$CHAT_ID'", "text":"Sending file: '$file'"}'
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument" \
              -F document=@"$file" \
              -F chat_id="$CHAT_ID"
          done