name: Send Files to Telegram

on:
  push:
    branches:
      - main
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  send_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Send files to Telegram and then send message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # GitHub username (Replace with your GitHub username)
          GITHUB_USERNAME="your_github_username"

          # Date of sending the file (format: YYYY-MM-DD)
          DATE=$(date +'%Y-%m-%d')

          # List of raw URLs of the files in the list/ directory
          FILES=(
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/export.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv4.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv6.json"
          )

          # Iterate through each file and send to Telegram
          for file_url in "${FILES[@]}"; do
            # Download the file
            curl -s -O $file_url

            # Get the filename from the URL
            FILENAME=$(basename $file_url)

            # Send the file to Telegram first
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument" \
              -F document=@"$FILENAME" \
              -F chat_id="$CHAT_ID"

            # Create the message text (this is sent after the file)
            MESSAGE_TEXT="Here is your file: $FILENAME.
Sent by: $GITHUB_USERNAME
Date: $DATE
Click the button to take an action.

https://t.me/Block_Script"

            # Send the message after the file is sent
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
              -d chat_id="$CHAT_ID" \
              -d text="$MESSAGE_TEXT"

            # Optionally, remove the file after sending
            rm -f "$FILENAME"
          done