name: Send Files to Telegram

on:
  push:
    branches:
      - main
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  send_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Send files to Telegram together
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # GitHub username (Replace with your GitHub username)
          GITHUB_USERNAME="your_github_username"

          # Date of sending the file (format: YYYY-MM-DD)
          DATE=$(date +'%Y-%m-%d')

          # List of raw URLs of the files in the list/ directory
          FILES=(
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/export.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv4.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv6.json"
          )

          # Download the files
          for file_url in "${FILES[@]}"; do
            curl -s -O $file_url
          done

          # Send all the files together in one message
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument" \
            -F document=@"export.json" \
            -F document=@"ipv4.json" \
            -F document=@"ipv6.json" \
            -F chat_id="$CHAT_ID" \
            -F caption="Sent by: $GITHUB_USERNAME
Date: $DATE
Click the button to take an action.

https://t.me/Block_Script"

          # Optionally, remove the files after sending
          rm -f export.json ipv4.json ipv6.json