name: Send Files to Telegram

on:
  push:
    branches:
      - main

jobs:
  send_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Send raw URLs to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # List of raw URLs of the files in the list/ directory
          FILES=(
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv4.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv6.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/export.json"
            # Add more URLs as needed
          )

          # Iterate over each URL and send it as a message to Telegram
          for file_url in "${FILES[@]}"; do
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
              -H "Content-Type: application/json" \
              -d '{"chat_id":"'$CHAT_ID'", "text":"Sending file URL: '$file_url'"}'
          done