name: IP Files

on:
  push:
    branches:
      - main

jobs:
  send_to_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Send files to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # List of raw URLs of the files in the list/ directory
          FILES=(
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/export.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv4.json"
            "https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv6.json"
            # Add more URLs as needed
          )

          # Download each file and send it to Telegram
          for file_url in "${FILES[@]}"; do
            # Download the file
            curl -s -O $file_url

            # Get the filename from the URL
            FILENAME=$(basename $file_url)

            # Send the file as a document to Telegram
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendDocument" \
              -F document=@"$FILENAME" \
              -F chat_id="$CHAT_ID"

            # Optionally, remove the file after sending
            rm -f "$FILENAME"
          done