name: IP Files

on:
  workflow_dispatch:  # Manual trigger via GitHub UI
  schedule:
    - cron: '0 * * * *'  # Trigger every hour at minute 0

jobs:
  send-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download files
      run: |
        curl -o export.json https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/export.json
        curl -o ipv4.json https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv4.json
        curl -o ipv6.json https://raw.githubusercontent.com/Json-Script/Collect_IPs/main/list/ipv6.json

    - name: Verify files
      run: |
        # Check if files were downloaded successfully
        ls -l export.json ipv4.json ipv6.json

    - name: Send files to Telegram bot
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
          -F chat_id="@Block_Script" \
          -F document=@export.json \
          -F caption="GitHub Username: Json-Script\nExport file containing all data."
        
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
          -F chat_id="@Block_Script" \
          -F document=@ipv4.json \
          -F caption="GitHub Username: Json-Script\nIPv4 addresses list."
        
        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
          -F chat_id="@Block_Script" \
          -F document=@ipv6.json \
          -F caption="GitHub Username: Json-Script\nIPv6 addresses list."