name: Send Telegram Message with File Content

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, modify as needed

jobs:
  sendTelegramMessage:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository (optional, if you want to work with any files in the repo)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install required Python packages
      - name: Install requests package
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run Python script to fetch file content and send Telegram message
      - name: Send message to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          import requests
          import os

          TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
          CHAT_ID = os.getenv('CHAT_ID')
          FILE_URL = "https://raw.githubusercontent.com/Json-Script/Collect_Keys/main/plus/full"

          def get_file_content(url):
              response = requests.get(url)
              if response.status_code == 200:
                  return response.text
              else:
                  raise Exception(f"Failed to retrieve file content. Status code: {response.status_code}")

          def send_telegram_message(token, chat_id, message):
              url = f"https://api.telegram.org/bot{token}/sendMessage"
              payload = {
                  "chat_id": chat_id,
                  "text": message
              }
              response = requests.post(url, json=payload)
              if response.status_code == 200:
                  print("Message sent successfully.")
              else:
                  print(f"Failed to send message. Status code: {response.status_code}, Response: {response.text}")

          try:
              file_content = get_file_content(FILE_URL)
              message = f"File Content:\n{file_content}"
              send_telegram_message(TELEGRAM_TOKEN, CHAT_ID, message)
          except Exception as e:
              print(f"An error occurred: {e}")